# ============================================================
# DAY 38/60 - CUSTOMER RETENTION & LIFETIME VALUE ANALYSIS
# 60 Days of Data Science
# ============================================================

import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
from pathlib import Path

# ============================================================
# PAGE CONFIG
# ============================================================

st.set_page_config(
    page_title="Day 38 - Customer Retention & CLV",
    page_icon="👥",
    layout="wide"
)

# ============================================================
# TITLE
# ============================================================

st.title("👥 Day 38: Customer Retention & Lifetime Value")
st.caption(
    "Customer Retention Analytics | Customer Lifetime Value | "
    "High-Value Customer Analysis"
)

st.markdown("""
This application analyzes customer retention and estimates
Customer Lifetime Value (CLV) using historical customer data.
""")

# ============================================================
# HELPER FUNCTIONS
# ============================================================

def find_column(columns, keywords):
    """
    Find a column based on common keyword patterns.
    """
    for keyword in keywords:
        for col in columns:
            if keyword in col.lower():
                return col
    return None


def prepare_data(df):
    """
    Automatically detect important customer columns.
    """

    columns = list(df.columns)

    customer_col = find_column(
        columns,
        [
            "customer_id",
            "customerid",
            "customer",
            "client_id",
            "client",
            "user_id",
            "userid"
        ]
    )

    date_col = find_column(
        columns,
        [
            "purchase_date",
            "transaction_date",
            "order_date",
            "date",
            "timestamp",
            "created_at"
        ]
    )

    revenue_col = find_column(
        columns,
        [
            "revenue",
            "amount",
            "sales",
            "purchase_amount",
            "order_value",
            "total_amount",
            "price",
            "spend"
        ]
    )

    return customer_col, date_col, revenue_col


def calculate_clv(df, customer_col, revenue_col):
    """
    Calculate simplified historical Customer Lifetime Value.

    CLV here represents historical customer revenue:
        CLV = Total Revenue generated by customer
    """

    customer_summary = (
        df.groupby(customer_col)
        .agg(
            Total_Revenue=(revenue_col, "sum"),
            Number_of_Transactions=(revenue_col, "count"),
            Average_Transaction_Value=(revenue_col, "mean")
        )
        .reset_index()
    )

    customer_summary["CLV"] = customer_summary["Total_Revenue"]

    return customer_summary


# ============================================================
# SIDEBAR
# ============================================================

st.sidebar.header("⚙️ Data Settings")

# Find CSV files in current directory
csv_files = sorted(Path(".").glob("*.csv"))

uploaded_file = st.sidebar.file_uploader(
    "Upload Customer CSV",
    type=["csv"]
)

selected_file = None

if uploaded_file is not None:
    df = pd.read_csv(uploaded_file)
    st.sidebar.success("Uploaded CSV loaded successfully!")

elif csv_files:
    file_names = [file.name for file in csv_files]

    selected_file = st.sidebar.selectbox(
        "Select existing CSV",
        file_names
    )

    df = pd.read_csv(selected_file)

else:
    df = None

# ============================================================
# DATA CHECK
# ============================================================

if df is None:

    st.warning("No CSV file found.")

    st.info("""
    Please upload a customer transaction CSV from the sidebar.

    Recommended columns:
    - Customer ID
    - Date / Transaction Date
    - Revenue / Amount / Sales
    """)

    st.stop()


# ============================================================
# RAW DATA
# ============================================================

st.subheader("📄 Dataset Preview")

st.dataframe(
    df.head(10),
    use_container_width=True
)

st.write(
    f"**Rows:** {df.shape[0]:,}  |  "
    f"**Columns:** {df.shape[1]}"
)

# ============================================================
# COLUMN DETECTION
# ============================================================

customer_col, date_col, revenue_col = prepare_data(df)

st.subheader("🔍 Detected Columns")

col1, col2, col3 = st.columns(3)

with col1:
    st.write("**Customer ID**")
    st.code(str(customer_col))

with col2:
    st.write("**Date Column**")
    st.code(str(date_col))

with col3:
    st.write("**Revenue Column**")
    st.code(str(revenue_col))


# ============================================================
# MANUAL COLUMN SELECTION
# ============================================================

st.sidebar.subheader("Column Mapping")

customer_col = st.sidebar.selectbox(
    "Customer ID Column",
    df.columns,
    index=list(df.columns).index(customer_col)
    if customer_col in df.columns else 0
)

date_col = st.sidebar.selectbox(
    "Date Column",
    df.columns,
    index=list(df.columns).index(date_col)
    if date_col in df.columns else 0
)

revenue_col = st.sidebar.selectbox(
    "Revenue / Amount Column",
    df.columns,
    index=list(df.columns).index(revenue_col)
    if revenue_col in df.columns else 0
)


# ============================================================
# DATA CLEANING
# ============================================================

df[date_col] = pd.to_datetime(
    df[date_col],
    errors="coerce"
)

df[revenue_col] = pd.to_numeric(
    df[revenue_col],
    errors="coerce"
)

df = df.dropna(
    subset=[customer_col, date_col, revenue_col]
)

df = df[df[revenue_col] >= 0]

if df.empty:
    st.error("No valid rows remain after data cleaning.")
    st.stop()


# ============================================================
# BASIC BUSINESS METRICS
# ============================================================

total_customers = df[customer_col].nunique()

total_revenue = df[revenue_col].sum()

total_transactions = len(df)

average_order_value = (
    total_revenue / total_transactions
    if total_transactions > 0 else 0
)

col1, col2, col3, col4 = st.columns(4)

with col1:
    st.metric(
        "👥 Total Customers",
        f"{total_customers:,}"
    )

with col2:
    st.metric(
        "💰 Total Revenue",
        f"₹{total_revenue:,.2f}"
    )

with col3:
    st.metric(
        "🛒 Transactions",
        f"{total_transactions:,}"
    )

with col4:
    st.metric(
        "💵 Avg Transaction",
        f"₹{average_order_value:,.2f}"
    )


# ============================================================
# CUSTOMER SUMMARY
# ============================================================

customer_summary = (
    df.groupby(customer_col)
    .agg(
        First_Purchase=(date_col, "min"),
        Last_Purchase=(date_col, "max"),
        Total_Revenue=(revenue_col, "sum"),
        Number_of_Transactions=(revenue_col, "count"),
        Average_Transaction_Value=(revenue_col, "mean")
    )
    .reset_index()
)

customer_summary["Customer_Lifetime_Days"] = (
    customer_summary["Last_Purchase"]
    - customer_summary["First_Purchase"]
).dt.days

customer_summary["Customer_Lifetime_Days"] = (
    customer_summary["Customer_Lifetime_Days"].clip(lower=1)
)

# Historical CLV
customer_summary["CLV"] = customer_summary["Total_Revenue"]


# ============================================================
# RETENTION ANALYSIS
# ============================================================

st.header("📈 Customer Retention Analysis")

max_date = df[date_col].max()

# Customers active in the latest 30 days
recent_start = max_date - pd.Timedelta(days=30)

recent_customers = set(
    df.loc[
        df[date_col] >= recent_start,
        customer_col
    ].unique()
)

# Customers active before the latest 30-day period
previous_customers = set(
    df.loc[
        df[date_col] < recent_start,
        customer_col
    ].unique()
)

retained_customers = (
    recent_customers.intersection(previous_customers)
)

if len(previous_customers) > 0:

    retention_rate = (
        len(retained_customers)
        / len(previous_customers)
        * 100
    )

else:

    retention_rate = 0


col1, col2, col3 = st.columns(3)

with col1:
    st.metric(
        "Previous Customers",
        f"{len(previous_customers):,}"
    )

with col2:
    st.metric(
        "Retained Customers",
        f"{len(retained_customers):,}"
    )

with col3:
    st.metric(
        "30-Day Retention Rate",
        f"{retention_rate:.2f}%"
    )


# ============================================================
# MONTHLY RETENTION TREND
# ============================================================

monthly_customer_activity = (
    df.set_index(date_col)
    .groupby(pd.Grouper(freq="ME"))[customer_col]
    .nunique()
    .reset_index()
)

monthly_customer_activity.columns = [
    "Month",
    "Active_Customers"
]

fig_retention = px.line(
    monthly_customer_activity,
    x="Month",
    y="Active_Customers",
    markers=True,
    title="Monthly Active Customer Trend"
)

fig_retention.update_layout(
    xaxis_title="Month",
    yaxis_title="Active Customers"
)

st.plotly_chart(
    fig_retention,
    use_container_width=True
)


# ============================================================
# CUSTOMER LIFETIME VALUE
# ============================================================

st.header("💰 Customer Lifetime Value Analysis")

average_clv = customer_summary["CLV"].mean()

median_clv = customer_summary["CLV"].median()

max_clv = customer_summary["CLV"].max()

col1, col2, col3 = st.columns(3)

with col1:
    st.metric(
        "Average CLV",
        f"₹{average_clv:,.2f}"
    )

with col2:
    st.metric(
        "Median CLV",
        f"₹{median_clv:,.2f}"
    )

with col3:
    st.metric(
        "Highest CLV",
        f"₹{max_clv:,.2f}"
    )


# ============================================================
# CLV DISTRIBUTION
# ============================================================

fig_clv = px.histogram(
    customer_summary,
    x="CLV",
    nbins=30,
    title="Customer Lifetime Value Distribution"
)

fig_clv.update_layout(
    xaxis_title="Customer Lifetime Value",
    yaxis_title="Number of Customers"
)

st.plotly_chart(
    fig_clv,
    use_container_width=True
)


# ============================================================
# HIGH-VALUE CUSTOMER GROUP
# ============================================================

st.header("⭐ High-Value Customer Analysis")

clv_threshold = customer_summary["CLV"].quantile(0.75)

customer_summary["Customer_Value_Group"] = np.where(
    customer_summary["CLV"] >= clv_threshold,
    "High Value",
    "Regular Value"
)

high_value_customers = customer_summary[
    customer_summary["Customer_Value_Group"] == "High Value"
]

regular_customers = customer_summary[
    customer_summary["Customer_Value_Group"] == "Regular Value"
]

col1, col2, col3 = st.columns(3)

with col1:
    st.metric(
        "High-Value Customers",
        f"{len(high_value_customers):,}"
    )

with col2:
    st.metric(
        "High-Value Revenue",
        f"₹{high_value_customers['CLV'].sum():,.2f}"
    )

with col3:
    st.metric(
        "75th Percentile CLV",
        f"₹{clv_threshold:,.2f}"
    )


# ============================================================
# CUSTOMER VALUE VISUALIZATION
# ============================================================

value_counts = (
    customer_summary["Customer_Value_Group"]
    .value_counts()
    .reset_index()
)

value_counts.columns = [
    "Customer_Group",
    "Customers"
]

fig_groups = px.bar(
    value_counts,
    x="Customer_Group",
    y="Customers",
    title="Customer Value Groups"
)

st.plotly_chart(
    fig_groups,
    use_container_width=True
)


# ============================================================
# TOP CUSTOMERS
# ============================================================

st.subheader("🏆 Top Customers by CLV")

top_customers = (
    customer_summary
    .sort_values(
        "CLV",
        ascending=False
    )
    .head(10)
)

st.dataframe(
    top_customers,
    use_container_width=True
)


# ============================================================
# TRANSACTION FREQUENCY
# ============================================================

st.header("🔄 Customer Purchase Frequency")

fig_frequency = px.histogram(
    customer_summary,
    x="Number_of_Transactions",
    nbins=20,
    title="Customer Transaction Frequency"
)

fig_frequency.update_layout(
    xaxis_title="Number of Transactions",
    yaxis_title="Customers"
)

st.plotly_chart(
    fig_frequency,
    use_container_width=True
)


# ============================================================
# CLV VS PURCHASE FREQUENCY
# ============================================================

fig_scatter = px.scatter(
    customer_summary,
    x="Number_of_Transactions",
    y="CLV",
    size="Average_Transaction_Value",
    hover_data=[customer_col],
    title="CLV vs Purchase Frequency"
)

fig_scatter.update_layout(
    xaxis_title="Number of Transactions",
    yaxis_title="Customer Lifetime Value"
)

st.plotly_chart(
    fig_scatter,
    use_container_width=True
)


# ============================================================
# RETENTION STRATEGIES
# ============================================================

st.header("💡 Recommended Retention Strategies")

st.markdown("""
### 1. Focus on High-Value Customers
High-value customers can be identified using CLV and transaction
frequency. Businesses can use loyalty programs and personalized
offers to maintain engagement.

### 2. Improve Repeat Purchases
Customers with low transaction frequency can be targeted with
reminders, personalized recommendations, and relevant offers.

### 3. Monitor Customer Activity
Tracking changes in customer activity can help identify customers
who may be becoming inactive.

### 4. Personalize Customer Experience
Customer purchase history can be used to create more relevant
communication and product recommendations.

### 5. Track Retention Over Time
Monthly retention and active-customer trends should be monitored
regularly to understand changes in customer behavior.
""")


# ============================================================
# BUSINESS INSIGHTS
# ============================================================

st.header("📊 Business Insights")

high_value_percentage = (
    len(high_value_customers)
    / total_customers
    * 100
    if total_customers > 0 else 0
)

high_value_revenue_percentage = (
    high_value_customers["CLV"].sum()
    / total_revenue
    * 100
    if total_revenue > 0 else 0
)

st.write(
    f"""
    • **{high_value_percentage:.2f}%** of customers fall into the
      high-value customer group.

    • These high-value customers contribute approximately
      **{high_value_revenue_percentage:.2f}%** of total historical revenue.

    • Average historical CLV is approximately
      **₹{average_clv:,.2f}**.

    • The calculated 30-day retention rate is
      **{retention_rate:.2f}%**.
    """
)


# ============================================================
# DOWNLOAD RESULTS
# ============================================================

st.header("⬇️ Export Analysis")

csv_data = customer_summary.to_csv(
    index=False
).encode("utf-8")

st.download_button(
    label="Download Customer CLV Analysis",
    data=csv_data,
    file_name="day38_customer_clv_analysis.csv",
    mime="text/csv"
)


# ============================================================
# FOOTER
# ============================================================

st.divider()

st.caption(
    "Day 38/60 | 60 Days of Data Science | "
    "Customer Retention & Lifetime Value Analysis"
)